version: '3.3'

services:
  crontab-ui:
    container_name: crontab-ui
    build: 
      context: .
      dockerfile: arm32v7-node.dockerfile
    image: local/arm32v7-crontab-ui:latest
    network_mode:
      - traefiknet
    volumes:
      - ./data/supervisord.conf:/etc/supervisord.conf:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cron.rule=Host(`${URL0_SAN}`)"
      - "traefik.http.routers.cron.entrypoints=websecure"
      - "traefik.http.routers.cron.service=api@internal"
      - "traefik.http.routers.cron.tls=true"
      - "traefik.http.routers.cron.tls.certresolver=mydnschallenge"
      - "traefik.http.middlewares.auth.basicauth.users=${CRON_LOGIN}"
      - "traefik.http.routers.api.middlewares=auth"

networks:
  traefiknet:
      external: true
